#pan_controller:
#    controller:
#        package: dynamixel_controllers
#        module: joint_position_controller
#        type: JointPositionController
#    joint_name: pan_joint
#    joint_speed: 2.0
#    motor:
#        id: 5
#        init: 512
#        min: 0
#        max: 1023



index_finger_proximal_phalange_flexor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: index_finger_proximal_phalange_flexor
    joint_speed: 3.0
    motor:
        id: 15
        init: 512
        min: 1024
        max: 2047


