index_finger_proximal_phalange_extensor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: index_finger_proximal_phalange_extensor
    joint_speed: 3.0
    motor:
        id: 8
        init: 512
        min: 0
        max: 2047
