index_finger_intermediate_phalange_flexor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: index_finger_intermediate_phalange_flexor
    joint_speed: 3.0
    motor:
        id: 11
        init: 512
        min: 0
        max: 2047
