ring_finger_intermediate_phalange_extensor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: ring_finger_intermediate_phalange_extensor
    joint_speed: 3.0
    motor:
        id: 14
        init: 512
        min: 1024
        max: 2047
