middle_finger_intermediate_phalange_flexor_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: middle_finger_intermediate_phalange_flexor
    joint_speed: 3.0
    motor:
        id: 6
        init: 512
        min: 1024
        max: 2047
